### ISSUE TITLE
Fix RSS feed

### ISSUE THREAD

**Issue by Murphinator2000** [jaredhaight/lgod#13]
RSS is not working for LGOD... can't see any LGOD updates in my RSS feed

**Comment by jaredhaight** [comment]
Need to setup a redirect for the old RSS url.

Old URL http://www.livegeekordie.com/index.php?format=feed&type=rss

**Comment by jaredhaight** [comment]
Old RSS URL is now set to redirect to new URL. If this doesn't fix the feed reader automatically, then people will have to re-subscribe with the new url (http://www.livegeekordie.com/feed/)

**Comment by jaredhaight** [comment]
Redirect was cached on my browser, need to tweak it a bit.

**Comment by jaredhaight** [comment]
Ok, now we're good.
