### ISSUE TITLE
Cannot insert some pics using the image insert tool

### ISSUE THREAD

**Issue by Murphinator2000** [jaredhaight/lgod#15]
I have some cases where I have no problem inserting an image but I have other times when I cannot get it to insert the image no matter how hard I try.  I have tried shrinking the image and changing the file type.  I have linked to the image as a workaround.

Example images: https://www.livegeekordie.com/article/adam-orth-twitter-and-the-firing-that/

**Comment by jaredhaight** [comment]
Issue is with images that are taller than 800px. When the image is uploaded, the height and width are checked, if either is above 800px resizeImage function is called to scale it down. In this case, it's being called as:

``` python
resizeImage('ac', self.image, 0, 800)
```

Which is all sorts of broken. Now that I think this through a little more, I'll just take out the check for how tall an image is. All we care about for the article content should be how wide it is.
