### ISSUE TITLE
Google search for Shining Force 3DS link is 404

### ISSUE THREAD

**Issue by Murphinator2000** [jaredhaight/lgod#17]
I did a search for Shining Force 3DS recently... if you go to the 2nd search page you will find the LGOD link.  It is pointing to: 
http://www.livegeekordie.com/index.php/games/handheld/1043-bring-shining-force-the-sword-of-hajya-to-3ds

This is a 404.  Can this be fixed?  Otherwise we will probably get less views from Google in the end.

**Comment by jaredhaight** [comment]
This is a duplicate of GH-10

**Comment by jaredhaight** [comment]
On closer look, the URL is a little different, I'll add it to GH-10
