### ISSUE TITLE
Facebook posts are getting broken

### ISSUE THREAD

**Issue by Murphinator2000** [jaredhaight/lgod#20]
Super Smash Bros updates article posted very fast with no picture or details.  Check Facebook page for LGOD to see the issue.

Is 404ing on a Droid phone, working on normal PC browser.

**Comment by jaredhaight** [comment]
This was a caching issue. The link got pushed out before the cache in varnish had expired.

The easiest way to address this will be to write a function that triggers when an article is published that clears the varnish cache.
