### ISSUE TITLE
Tags disappearing

### ISSUE THREAD

**Issue by Murphinator2000** [jaredhaight/lgod#22]
I can't seem to center iframes anymore.  I used to use p align="center" and that works for old articles.  I know it is old HTML but it was the only thing that seemed to work.  Old code seems to work fine (Nintendo Directs).  In the latest Shaq-Fu article it seems like I can't center an iframe anymore.

**Comment by jaredhaight** [comment]
For alignment, don't use "align=center", that's not supported in HTML5. Please use the CSS class "center" instead.

``` html
<p class="center">Example Content</p>
```

Please let me know if you find any other tags that are no longer working.
